### ISSUE TITLE
Exception from call site #0 bootstrap method.

### ISSUE THREAD

**Issue by unix14** [TutorialsAndroid/VSpot#1]
Hey,
im trying to implement your library in my project, and i keep getting this, inside a fragment

 java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.developer.spoti.vspoti.VSpotView.<init>(VSpotView.java:88)
        at com.developer.spoti.vspoti.VSpotView.<init>(VSpotView.java:24)
        at com.developer.spoti.vspoti.VSpotView$Builder.build(VSpotView.java:399)

**Comment by TutorialsAndroid** [comment]
> Hey,
> im trying to implement your library in my project, and i keep getting this, inside a fragment
> 
> java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
> at com.developer.spoti.vspoti.VSpotView.(VSpotView.java:88)
> at com.developer.spoti.vspoti.VSpotView.(VSpotView.java:24)
> at com.developer.spoti.vspoti.VSpotView$Builder.build(VSpotView.java:399)

Firstly, sorry for late reply. I will check this issue. But I think instead of using this library in fragment I would suggest to use this library in main activity where you load your fragment in main and then call the view wherever you want.
